#!/bin/sh
set -e

# Automatically added by dhpython:
if which pyclean >/dev/null 2>&1; then
	pyclean -p system-config-samba-focal 
else
	dpkg -L system-config-samba-focal | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
